package:
  name: perl-sanger-cgp-vcf
  version: '2.0.4'

source:
  fn: cgpVcf-v2.0.4.tar.gz
  url: https://github.com/cancerit/cgpVcf/archive/v2.0.4.tar.gz

build:
  number: 2
  skip: True # [osx]

requirements:
  build:
    - gcc
    - perl-threaded
    - perl-app-cpanminus
    - perl-module-build
    - perl-data-uuid
    - perl-vcftools-vcf
  run:
    - libgcc
    - perl-threaded
    - perl-data-uuid
    - perl-vcftools-vcf

test:
  imports:
    - Sanger::CGP::Vcf

about:
  home: https://github.com/cancerit/cgpVcf
  license: GPLv3
  summary: a set of common perl utilities for generating consistent Vcf headers
