package:
  name: perl-sanger-cgp-battenberg
  version: '1.5.3'

source:
  git_url: https://github.com/cancerit/cgpBattenberg.git
  git_rev: 1.5.3

build:
  number: 1
  skip: True # [osx]

requirements:
  build:
    - gcc
    - perl-threaded
    - perl-app-cpanminus
    - perl-module-build
    - perl-file-sharedir
    - perl-file-sharedir-install
    - perl-pcap
    - perl-sanger-cgp-allelecount
    - perl-bio-db-hts
    - cancerit-allelecount
    - impute2
  run:
    - libgcc
    - htslib
    - perl-threaded
    - perl-file-sharedir
    - perl-file-sharedir-install
    - perl-pcap
    - perl-sanger-cgp-allelecount
    - perl-bio-db-hts
    - r
    - r-rcolorbrewer
    - cancerit-allelecount
    - impute2

test:
  commands:
    - "perl -e 'import Sanger::CGP::Battenberg;'"
    - "battenberg.pl 2>&1 | grep battenberg.pl"

about:
  home: https://github.com/cancerit/cgpBattenberg
  license: GPLv3
  summary: detect subclonality and copy number in matched NGS data
